name: VIRSORTER2_RUN
description: Runs VirSorter2 to identify viral sequences in metagenomic data
keywords:
  - viralrecon
  - metagenomics
  - virus
  - identification
tools:
  - virsorter2:
      description: A multi-classifier, expert-guided approach to detect diverse DNA and RNA virus genomes
      homepage: https://github.com/jiarong/VirSorter2
      documentation: https://github.com/jiarong/VirSorter2/wiki
      tool_dev_url: https://github.com/jiarong/VirSorter2
      doi: "10.1186/s40168-020-00990-y"
      licence: ["GPL-3.0"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fasta:
      type: file
      description: Input FASTA file
      pattern: "*.{fa,fasta}"
  - db:
      type: directory
      description: Directory containing VirSorter2 database files
      pattern: "*"

output:
  - boundary:
      type: file
      description: Final viral boundary file
      pattern: "final-viral-boundary.tsv"
  - fasta:
      type: file
      description: Final viral combined FASTA file
      pattern: "final-viral-combined.fa"
  - score:
      type: file
      description: Final viral score file
      pattern: "final-viral-score.tsv"
  - log:
      type: directory
      description: Directory containing log files
      pattern: "log"
  - config:
      type: file
      description: Configuration file
      pattern: "config.yaml"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@your_github_username"
