report_comment: >
  bacpaq is a bioinformatics best-practice pipeline for bacterial genomic analysis for short-reads (Illumina) and long-reads (Oxford Nanopore) sequencing data. Currently bacpaq supports WGS-based analyses.

report_section_order:
  "cidgoh-bacpaq-methods-description":
    order: -1000
  software_versions:
    order: -1001
  "cidgoh-bacpaq-summary":
    order: -1002

export_plots: true
disable_version_detection: true
data_format: "yaml"

run_modules:
  - custom_content
  - fastqc
  - fastp
  - trimmomatic
  - porechop
  - fastqc
  - kraken
  - bracken
  - quast
  - prokka
  - bakta
  - busco
  - snippy

# prettify headings of report
custom_logo_url: https://github.com/cidgoh/bacpaq/
custom_logo_title: "cidgoh/bacpaq"
title: "BACPAQ"

#
# Module order
#

top_modules:
  - custom_content:
      name: "Dummy section"
      anchor: "dummy_section"
      info: "Dummy section"
  - "fastqc":
      name: "FastQC: raw reads"
      path_filters_exclude:
        - "*trimmed*"
  - "fastp":
      name: "FastP"
      info: "Read preprocessing."
      path_filters:
        - "*fastp.json"
  - "trimmomatic":
      name: "Trimmomatic"
      info: "Adapter trimming for Illumina reads."
      path_filters:
        - "*trimmomatic.log"
  - "porechop":
      name: "Porechop"
      info: "Adapter trimming for Oxford Nanopore reads."
      path_filters:
        - "*porechop.log"
  - "fastqc":
      name: "FastQC: after preprocessing"
      anchor: "FastQC_trimmed"
      info: "After trimming and, if requested, contamination removal."
      path_filters:
        - "*trimmed*"
  - "kraken":
      name: "Kraken2"
      anchor: "Kraken2"
      target: "Kraken2"
      doi: "10.1101/gr.210641.116"
      path_filters:
        - "*.kraken2.report.txt"
      top_n: 10
  - "kraken":
      name: "Centrifuge"
      anchor: "centrifuge"
      target: "Centrifuge"
      doi: "10.1101/gr.210641.116"
      info: "is a very rapid and memory-efficient system for the classification of DNA sequences from microbial samples. The system uses a novel indexing scheme based on the Burrows-Wheeler transform (BWT) and the Ferragina-Manzini (FM) index. Note: Figure title"
      extra: "ℹ️: plot title will say Kraken2 due to Centrifuge producing the same output format as Kraken. If activated, see the actual Kraken2 results in the section above."
      path_filters:
        - "*.centrifuge_kreport.txt"
  - "bracken":
      name: "bracken"
      anchor: "bracken"
      target: "bracken"
      info: "Estimates the abundance of species in metagenomic samples."
      contents_re: ^(\d{1,3}\.\d{1,2})\t(\d+)\t(\d+)\t((\d+)\t(\d+)\t)?([URDKPCOFGS-]\d{0,2})\t(\d+)(\s+)root
      num_lines: 1
      path_filters:
        - "*.bracken.report.tsv"
  - "quast":
      name: "QUAST: assembly"
      info: "Assembly statistics of binned assemblies."
      path_filters_exclude:
        - "*rawassemblies.tsv"
      contents: "Assembly\t"
      num_lines: 2
  - "busco":
      info: "assesses genome assembly and annotation completeness with Benchmarking Universal Single-Copy Orthologs. In case BUSCO's automated lineage selection was used, only generic results for the selected domain are shown and only for genome bins and kept, unbinned contigs for which the BUSCO analysis was successfull, i.e. not for contigs for which no BUSCO genes could be found. Bins for which a specific virus lineage was selected are also not shown."
      fn: short_summary*
      contents: "BUSCO version is:"
      num_lines: 1
  - "prokka":
      name: "Prokka"
      info: "Prokka is a software tool for the rapid annotation of prokaryotic genomes."
      contents: "contigs:"
      fn: "*.txt"
  - "bakta":
      name: "Bakta"
      info: "Bakta is a software tool for the rapid annotation of prokaryotic genomes."
      contents: "Bakta:"
      fn: "*.txt"
  - "snippy/snippy":
      name: "Snippy"
      info: "Snippy is a tool for rapid bacterial variant calling and annotation."
      contents: "snippy"
      fn: "*.txt"
  - "snippy/snippy-core":
      name: "Snippy core"
      info: "Snippy core is a tool for rapid bacterial variant calling and annotation."
      contents_re: "ID\tLENGTH\tALIGNED\tUNALIGNED\tVARIANT\tHET\tMASKED\tLOWCOV"
      num_lines: 1
      fn: "*.txt"

sp:
  kraken:
    fn_re: ".*[kraken2|centrifuge].*report.txt"
  quast:
    fn_re: ".*report.tsv"

## Tool specific configuration
prokka_fn_snames: True

#
# clean names
#

fn_clean_exts:
  - ".gz"
  - ".fastq"
  - ".txt"
  - ".report.txt"

extra_fn_clean_exts:
  - type: regex
    pattern: "_T{1,2}.*"

# add a proper label to contig stats
sample_names_replace_regex: True
sample_names_replace:
  "(^.*\\w)_(illumina$|nanopore$)": "\\1_\\2_assembly"

# merge paired end samples
table_sample_merge:
  "[Read 1]":
    - type: regex
      pattern: "_[rR]?1$"
  "[Read 2]":
    - type: regex
      pattern: "_[rR]?2$"
  "Nanopore":
    - type: regex
      pattern: "_nanopore_reads$"

#
# General Stats table customization
#

table_columns_visible:
  "FastQC: raw reads":
    avg_sequence_length: True
  "FastQC: after preprocessing":
    avg_sequence_length: True
  "fastp": False
  "Kraken2": False
  "Centrifuge": False
  "QUAST: assembly":
    N75: True
    L50: True
    L75: True
    "Largest contig": True
    "Total length": True
    N50: True
  "Prokka":
    Organism: False
  "Bakta":
    Organism: False

table_columns_placement:
  "FastQC: raw reads":
    percent_duplicates: 1000
    percent_gc: 1100
    avg_sequence_length: 1200
    median_sequence_length: 1300
    total_sequences: 1400
    percent_fails: 1500
  "FastQC: after preprocessing":
    percent_duplicates: 2000
    percent_gc: 2100
    avg_sequence_length: 2200
    median_sequence_length: 2300
    total_sequences: 2400
    percent_fails: 2500
  "fastp":
    pct_duplication: 3000
    after_filtering_q30_rate: 3100
    after_filtering_q30_bases: 3200
    filtering_result_passed_filter_reads: 3300
    after_filtering_gc_content: 3400
    pct_surviving: 3500
    pct_adapter: 3600
  "Kraken2":
    "% root": 8000
    "% Top 5": 8100
    "% Unclassified": 8200
  "Centrifuge":
    "% root": 9000
    "% Top 5": 9100
    "% Unclassified": 9200
  "QUAST: assembly":
    "N50": 10000
    "Total length": 11000
  Prokka:
    contigs: 20000
    bases: 21000
    CDS: 22000
    plasmid: 23000
    organism: 23500
  Bakta:
    contigs: 24000
    bases: 25000
    CDS: 26000
    plasmid: 27000
    organism: 2750

table_columns_name:
  "FastQC: raw reads":
    percent_duplicates: "% Dups (raw)"
    percent_gc: "% GC (raw)"
    avg_sequence_length: "Avg. length (raw)"
    median_sequence_length: "Median length (raw)"
    total_sequences: "M Seqs (raw)"
    percent_fails: "% Fails (raw)"
  "FastQC: after preprocessing":
    percent_duplicates: "% Dups (processed)"
    percent_gc: "% GC (processed)"
    avg_sequence_length: "Avg. length (processed)"
    median_sequence_length: "Median length (processed)"
    total_sequences: "M Seqs (processed)"
    percent_fails: "% Fails (processed)"
  "Prokka":
    contigs: "Contigs annotated (n)"
  "Bakta":
    contigs: "Contigs annotated (n)"

custom_table_header_config:
  general_stats_table:
    "Total length":
      hidden: True
    N50:
      hidden: True
