name: "nf-test Action"
description: "Runs nf-test for a specific module and profile"
inputs:
  profile:
    description: "Profile to use (singularity, docker, or conda)"
    required: true
  module:
    description: "Module to test"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Setup Nextflow
      uses: nf-core/setup-nextflow@v2
      with:
        version: "${{ env.NXF_VER }}"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install nf-test
      uses: nf-core/setup-nf-test@v1
      with:
        version: "${{ env.NFT_VER }}"
        install-pdiff: true

    - name: Setup apptainer
      if: inputs.profile == 'singularity'
      uses: eWaterCycle/setup-apptainer@main

    - name: Set up Singularity
      if: inputs.profile == 'singularity'
      shell: bash
      run: |
        mkdir -p ${{ env.NXF_SINGULARITY_CACHEDIR }}
        mkdir -p ${{ env.NXF_SINGULARITY_LIBRARYDIR }}

    - name: Conda setup
      if: inputs.profile == 'conda'
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        conda-solver: libmamba
        conda-remove-defaults: true

    - name: Set up nextflow secrets
      if: env.SENTIEON_ENCRYPTION_KEY != '' && env.SENTIEON_LICENSE_MESSAGE != ''
      shell: bash
      run: |
        python -m pip install cryptography
        nextflow secrets set SENTIEON_AUTH_DATA $(python3 tests/modules/nf-core/sentieon/license_message.py encrypt --key "$SENTIEON_ENCRYPTION_KEY" --message "$SENTIEON_LICENSE_MESSAGE")

    - name: Run nf-test
      shell: bash
      env:
        SENTIEON_LICSRVR_IP: ${{ env.SENTIEON_LICSRVR_IP }}
        SENTIEON_AUTH_MECH: "GitHub Actions - token"
        NFT_WORKDIR: "~"
      run: |
        cd modules/nf-core/${{ inputs.module }}
        nf-test test \
          --profile=${{ inputs.profile }} \
          --tap=test.tap \
          --verbose \
          --ci \
          --filter process,workflow

    - uses: pcolby/tap-summary@v1
      with:
        path: modules/nf-core/${{ inputs.module }}/test.tap

    - name: Clean up
      if: always()
      shell: bash
      run: |
        sudo rm -rf /home/ubuntu/tests/
