name: Test nf-core Modules

on:
  push:
    branches:
      - "github_actions_mza"
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NXF_ANSI_LOG: false

jobs:
  discover-modules:
    # ... (keep this job as is) ...

  test-modules:
    needs: discover-modules
    runs-on: ubuntu-latest
    container:
      image: nfcore/tools:latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.discover-modules.outputs.module_list) }}
    name: Test nf-core Module ${{ matrix.module }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run nf-test for ${{ matrix.module }}
        run: |
          echo "Testing module: ${{ matrix.module }}"
          nf-test test --module ${{ matrix.module }}

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nf-test-results-${{ matrix.module }}
          path: .nf-test/
