name: Test nf-core Modules

on:
  push:
    branches:
      - 'github_actions_mza'
  pull_request:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NXF_ANSI_LOG: false

jobs:
  discover-modules:
    name: Discover nf-core Modules
    runs-on: ubuntu-latest
    outputs:
      module_list: ${{ steps.get-modules.outputs.module_list }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List nf-core Modules
        id: get-modules
        run: |
          modules=$(find modules -type d -maxdepth 1 -mindepth 1 -exec basename {} \; | jq -R -s -c 'split("\n")[:-1]')
          if [ -z "$modules" ]; then
            echo "No modules found!"
            exit 1
          fi
          echo "module_list=${modules}" >> $GITHUB_OUTPUT
        shell: bash

  test-modules:
    needs: discover-modules
    runs-on: ubuntu-latest
    container:
      image: nfcore/tools:latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.discover-modules.outputs.module_list) }}
    name: Test nf-core Module ${{ matrix.module }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: '24.10.1'

      - name: Run nf-test for ${{ matrix.module }}
        run: |
          echo "Testing module: ${{ matrix.module }}"
          nf-test test --module ${{ matrix.module }}
