name: Test nf-core Modules

on:
  push:
    branches:
      - "github_actions_mza"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NXF_ANSI_LOG: false
  NFT_VER: "0.9.2" # nf-test version

jobs:
  discover-modules:
    name: Discover nf-core Modules
    runs-on: ubuntu-latest
    outputs:
      module_list: ${{ steps.get-modules.outputs.module_list }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List nf-core Modules
        id: get-modules
        run: |
          modules=$(find modules -type d -maxdepth 1 -mindepth 1 -exec basename {} \;)
          modules_json=$(printf '%s\n' "${modules}" | jq -R . | jq -s .)
          echo "::set-output name=module_list::${modules_json}"
        shell: bash

  test-modules:
    needs: discover-modules
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.discover-modules.outputs.module_list) }}
    name: Test nf-core Module: ${{ matrix.module }}
    steps:
      # Clean workspace
      - name: Clean Workspace
        run: |
          rm -rf $GITHUB_WORKSPACE/*

      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Nextflow
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "24.10.1"

      # Run nf-test for the module
      - name: Run nf-test for ${{ matrix.module }}
        run: |
          echo "Testing module: ${{ matrix.module }}"
          nf-test --module ${{ matrix.module }}
