name: Notify Slack on New Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.CIDGOH_SLACK_WEBHOOK }}
        run: |
          RELEASE_NOTES=$(echo "${{ github.event.release.body }}" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
          curl -X POST -H 'Content-type: application/json' --data \
          "{\"text\":\"A new release has been published: <${{ github.event.release.html_url }}|${{ github.event.release.tag_name }}> by *${{ github.event.release.author.login }}*.\n\n*Release Notes:* \n${RELEASE_NOTES}\n\n**Full Changelog**: <${{ github.event.release.html_url }}/compare/${{ github.event.release.tag_name }}...previous-tag>\"}" \
          $SLACK_WEBHOOK_URL
