name: BACPAQ Full Workflow CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
      - master
      - github_actions_jl
  pull_request:
  workflow_dispatch:

env:
  NXF_ANSI_LOG: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name == 'push' ||  github.event_name == 'pull_request' || github.repository == 'cidgoh/bacpaq' }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "23.04.0"
        BACPAQ_TEST_CONFIG:
          - "test"
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # - name: Disk space cleanup
      #   uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1

      - name: Set up pipeline pre-reqs
        run: |
          curl https://object-arbutus.cloud.computecanada.ca/cidgohshare/database/tar/adaptors.tar.gz -o adaptors.tar.gz
          tar -xzvf adaptors.tar.gz
          curl https://object-arbutus.cloud.computecanada.ca/cidgohshare/database/tar/busco_bacteria_odb10.tar.gz -o busco_bacteria_odb10.tar.gz
          tar -xzvf busco_bacteria_odb10.tar.gz
          curl https://object-arbutus.cloud.computecanada.ca/cidgohshare/database/tar/confindr.tar.gz -o confindr.tar.gz
          tar -xzvf confindr.tar.gz
          curl https://genome-idx.s3.amazonaws.com/kraken/k2_viral_20240605.tar.gz -o k2_viral_20240605.tar.gz
          tar -xzvf k2_viral_20240605.tar.gz
          curl https://genome-idx.s3.amazonaws.com/centrifuge/p_compressed%2Bh%2Bv.tar.gz -o centrifuge.tar.gz
          tar -xzvf centrifuge.tar.gz
          ls

      - name: Run pipeline with test data
        # TODO nf-core: You can customise CI pipeline run tests as required
        # For example: adding multiple test runs with different parameters
        # Remember that you can parallelise this by using strategy.matrix
        run: |
          mkdir ./kraken2_db
          mkdir ./checkm_db
          mkdir ./confindr_db
          mkdir ./busco_db
          mkdir ./bakta_db
          touch ./adapters.fa

          nextflow run ${GITHUB_WORKSPACE} \
            -profile ${{ matrix.BACPAQ_TEST_CONFIG }},docker \
            --outdir ./results
